// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_generate from "./routes/api/generate.ts";
import * as $api_health from "./routes/api/health.ts";
import * as $api_index from "./routes/api/index.ts";
import * as $docs from "./routes/docs.tsx";
import * as $index from "./routes/index.tsx";
import * as $GeneratorForm from "./islands/GeneratorForm.tsx";
import * as $ResultPanel from "./islands/ResultPanel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/generate.ts": $api_generate,
    "./routes/api/health.ts": $api_health,
    "./routes/api/index.ts": $api_index,
    "./routes/docs.tsx": $docs,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/GeneratorForm.tsx": $GeneratorForm,
    "./islands/ResultPanel.tsx": $ResultPanel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
